apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${project.artifactId}
  namespace: default
spec:
  template:
    spec:
      containers:
       - name:  ${project.artifactId}
         livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30        
         env:
         - name: SPRING_PROFILES_ACTIVE
           value: kubernetes
         - name: USERNAME
           valueFrom:
             configMapKeyRef:
                name: user-config
                key: name

                       
 